version: '3'

services:
  jekyll:
    image: jekyll/jekyll
    environment:
        - JEKYLL_ENV=development
    volumes: 
      - ./:/srv/jekyll:Z
    ports:
      - 4000:4000
    command: jekyll serve
          